version: '3'
services:
  app_test:
    container_name: full_app_test
    build:
      context: .
      dockerfile: ./Dockerfile.test
    volumes:
      - api_test:/app/src/app/
    depends_on:
      - postgres_test
    networks:
      - go_rest_test

  postgres_test:
    image: postgres:latest
    container_name: full_db_test_postgress
    environment:
      - POSTGRES_USER=${TEST_DB_USER}  
      - POSTGRES_PASSWORD=${TEST_DB_PASSWORD}
      - POSTGRES_DB=${TEST_DB_NAME}
      - DATABASE_HOST=${TEST_DB_HOST} 
    ports:
      - '5433:5432'
    volumes:
      - database_postgres_test:/var/lib/postgresql/data
    networks:
      - go_rest_test
    command: -p 5433

volumes:
  api_test:
  database_postgres_test:

# Networks to be created to facilitate communication between containers
networks:
  go_rest_test:
#    driver: bridge

